name: sort

on:
  push:
    branches: [ "main" ]
    paths: ["timeline.csv"]
  workflow_dispatch:

jobs:
  sort_timeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Sort timeline according to start date
        run: |
          (head -n 1 timeline.csv && tail -n +2 timeline.csv | sort -k 1) > tmp
          mv tmp > timeline.csv
      - name: Commit sorted timeline
        run: |
          git config user.name 'julia ferraioli'
          git config user.email 'me@juliaferraioli.com'
          git add timeline.csv
          git commit -m "Generated commit to automatically sort the timeline upon push"
          git push
        
